# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-24 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funfacts_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.CharField(default='sports', max_length=50),
            preserve_default=False,
        ),
    ]
